apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835-project
  region: "us-east-1"
  version: "1.31"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

iam:
  serviceRoleARN: arn:aws:iam::767398074604:role/LabRole

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 2
    instanceType: t3.medium
    volumeSize: 50
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::767398074604:role/LabRole 