apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: project
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: clo835
      containers:
      - name: flask-app
        image: 767398074604.dkr.ecr.us-east-1.amazonaws.com/clo835-final-project:latest
        ports:
        - containerPort: 81
        env:
        - name: PORT
          value: "81"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: STUDENT_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: STUDENT_NAME
        - name: BACKGROUND_IMAGE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKGROUND_IMAGE_URL
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_BUCKET
        - name: S3_IMAGE_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_IMAGE_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 81
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 81
          initialDelaySeconds: 5
          periodSeconds: 5 