apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: final
data:
  BACKGROUND_IMAGE_URL: "https://clo835-final-project-s3b.s3.us-east-1.amazonaws.com/background.jpg"
  STUDENT_NAME: "Amardeep Puri"
  S3_BUCKET: "clo835-final-project-s3b"
  S3_IMAGE_KEY: "background.jpg"
  DB_NAME: "clo835_db" 